// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2FXUPjGRYTxCSss5_JtF5H3T6dCUb4sM',
    appId: '1:762822830497:web:b729c9119c7a8c01d143e0',
    messagingSenderId: '762822830497',
    projectId: 'pilates-studio-da2a9',
    authDomain: 'pilates-studio-da2a9.firebaseapp.com',
    storageBucket: 'pilates-studio-da2a9.firebasestorage.app',
    measurementId: 'G-Y9F3R7YRWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcPKZtZo4AEd_UG9nFQYchdlvsnmMYiM0',
    appId: '1:762822830497:android:e49d7131abdb1e59d143e0',
    messagingSenderId: '762822830497',
    projectId: 'pilates-studio-da2a9',
    storageBucket: 'pilates-studio-da2a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfYcPA_EhjPBPQ5ajxbEqTYN-cKNhIhQ',
    appId: '1:762822830497:ios:8a5d830d1943e045d143e0',
    messagingSenderId: '762822830497',
    projectId: 'pilates-studio-da2a9',
    storageBucket: 'pilates-studio-da2a9.firebasestorage.app',
    iosClientId: '762822830497-6b6s9fet37425mv977pdvdnek2gounn0.apps.googleusercontent.com',
    iosBundleId: 'com.crumbtech.pilatesstudiolilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmfYcPA_EhjPBPQ5ajxbEqTYN-cKNhIhQ',
    appId: '1:762822830497:ios:8a5d830d1943e045d143e0',
    messagingSenderId: '762822830497',
    projectId: 'pilates-studio-da2a9',
    storageBucket: 'pilates-studio-da2a9.firebasestorage.app',
    iosClientId: '762822830497-6b6s9fet37425mv977pdvdnek2gounn0.apps.googleusercontent.com',
    iosBundleId: 'com.crumbtech.pilatesstudiolilla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2FXUPjGRYTxCSss5_JtF5H3T6dCUb4sM',
    appId: '1:762822830497:web:24a58d8f77efe7e3d143e0',
    messagingSenderId: '762822830497',
    projectId: 'pilates-studio-da2a9',
    authDomain: 'pilates-studio-da2a9.firebaseapp.com',
    storageBucket: 'pilates-studio-da2a9.firebasestorage.app',
    measurementId: 'G-ETJT7K7XPR',
  );
}
